# Generated by Django 3.2.6 on 2023-11-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_first_name', models.CharField(max_length=50)),
                ('applicant_last_name', models.CharField(max_length=50)),
                ('applicant_cv', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
