# Generated by Django 5.0.1 on 2024-02-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applicant_data_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_data',
            name='actual_skills',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_data',
            name='no_of_pages',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_data',
            name='recommended_skills',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_data',
            name='resume_score',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_data',
            name='user_level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
